version: '3.8'

services:
  duplidash:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: duplidash
    restart: unless-stopped
    ports:
      - "9666:9666"
    volumes:
      - duplidash_data:/app/data
    environment:
      - NODE_ENV=production
      - PORT=9666
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:9666"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  duplidash_data:
    name: duplidash_data 